name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 3.0.0
homepage: https://github.com/mmcc007/screenshots

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  path: ^1.8.0
  file: ^6.1.2
  archive: ^3.1.2
  platform: ^3.0.0
  process: ^4.2.3
  meta: ^1.7.0
  intl: ^0.17.0
  tool_mobile:
    git: https://github.com/felixgabler/tool_mobile.git

dev_dependencies:
  test: any
  mockito: ^5.0.16
  pedantic: ^1.11.1
  quiver: ^3.0.1+1
  collection: any

executables:
  screenshots: main
